- name: Base Server Setup
  hosts: localhost
  become: true
  tasks:
    - name: Ensure unattended-upgrades is installed
      apt:
        name: unattended-upgrades
        state: present
        update_cache: yes

    - name: Configure automatic security updates
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";

    - name: Enable and start unattended-upgrades service
      systemd:
        name: unattended-upgrades
        enabled: yes
        state: started
